### ISSUE TITLE
Potion Blender registers `potionblender:brewing_cauldron_recipe` twice, causing EMI to fail to load

### ISSUE THREAD

**Issue by Zhaith-Izaliel** [motivational-dragon/Potion-Blender#12]
Hi!

Potion Blender is loading 2 recipes for `potionblender:brewing_cauldron_recipe` causing the exception below. This exception effectively stops EMI (a JEI like client) to load properly when opening the inventory.

## Informations

- Mod Version: 3.1.0
- Game Version: 1.20.1
- Mod Loader: Fabric
- Fabric API Version: 0.92.1+1.20.1
- Mod Loaded:
  - Fabric API (0.92.1+1.20.1)
  - EMI (1.1.6+1.20.1)
  - Potion Blender (3.1.0)

## Trace

The Below trace is the exerpt when the exception happens (just after loading EMI), if you want the full log I can give it to you.

```
[21:18:27] [Render thread/INFO]: [EMI] Joining server, EMI waiting for data from server...
[21:18:27] [Render thread/ERROR]: Error executing task on Client
java.lang.IllegalStateException: Duplicate recipe ignored with ID potionblender:brewing_cauldron_recipe
	at net.minecraft.class_1863.method_20704(class_1863.java:149) ~[client-intermediary.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.minecraft.class_1863.method_20702(class_1863.java:143) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11106(class_634.java:1440) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_11997(class_2788.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_11054(class_2788.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
[21:18:27] [Render thread/INFO]: [EMI] Recipes synchronized, waiting for tags to reload EMI...
[21:18:28] [Render thread/INFO]: Loaded 2 advancements
[21:18:34] [Server thread/INFO]: Saving and pausing game...
```

**Comment by Zhaith-Izaliel** [comment]
Hi, I checked the new fix you recently pushed with EMI, and it works. Thank you for your reactivity !

I'll close this issue as resolved :)
